#!/bin/sh
DASHI="" INIARG=""
HALLIB_DIR=/usr/share/linuxcnc/hallib; export HALLIB_DIR
LINUXCNC_TCL_DIR=/usr/lib/tcltk/linuxcnc; export LINUXCNC_TCL_DIR
if [ $# -ne 1 ]; then echo 1>&2 Usage: "$0" inifile; exit 1; fi
exec haltcl -i "$1" /usr/lib/tcltk/linuxcnc/twopass.tcl
